Update 020_ros_with_dds.md
ros2/design pull request #293
Opened 2020-07-07 10:33 UTC by RamziKaroui

Add a reference to the new Tier-1 Cyclone DDS implementation and added some insights on OpenspliceDDS implementation

2020-07-07 13:03 UTC, gbiggs requested changes

2020-07-07 13:03 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
```suggestion
From ADLINK's website, they support TCP as of OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
```

2020-07-07 13:03 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
What version do they support shared memory as a transport from, and what version do they support an in-memory database from?

2020-07-07 13:03 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +ADLINK also supports heavily the Eclipse Cyclone DDS implementation [https://github.com/eclipse-cyclonedds/cyclonedds] (https://www.adlinktech.com/en/CycloneDDS).  Cyclone DDS is licensed under Eclip
```suggestion
ADLINK also contributes to Eclipse Cyclone DDS [https://github.com/eclipse-cyclonedds/cyclonedds] (https://www.adlinktech.com/en/CycloneDDS).  Cyclone DDS is licensed under the Eclipse Public License - v 2.0 ( https://www.eclipse.org/legal/epl-2.0/).
```

2020-07-07 13:03 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +So, just as an example, if the default implementation is Connext, but someone wants to use one of the LGPL options like OpenSplice, FastRTPS or Cyclone DDS, they simply need to recompile the ROS sour
Cyclone DDS is not LGPL. Actually, neither is Fast DDS...

```suggestion
So, just as an example, if the default implementation is Connext, but someone wants to use one of the Apache 2 options like Fast DDS or Cyclone DDS, they simply need to recompile the ROS source code with some options flipped and they can use the implementation of their choice.
```

2020-07-07 14:49 UTC, RamziKaroui commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
OpenSpliceDDS ( initially called SPLICE) was actually built from the begging with as in-memory eventually consistent database , See slides 8 of Erik Boasson on the different spirits that  were the DDS technology ( https://static1.squarespace.com/static/51df34b1e4b08840dcfd2841/t/5d102784919bd40001a4059d/1561339788292/2_3_Boasson.pdf ) 

More details on this link
http://download.prismtech.com/docs/Vortex/html/ospl/DeploymentGuide/overview.html#shared-memory-architecture

2020-07-07 23:09 UTC, dirk-thomas commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
Isn't the shared memory transport only available in the commericial version but not in the community edition?

2020-07-07 23:09 UTC, dirk-thomas commented on articles/020_ros_with_dds.md
> +ADLINK also contributes to Eclipse Cyclone DDS [https://github.com/eclipse-cyclonedds/cyclonedds] (https://www.adlinktech.com/en/CycloneDDS).  Cyclone DDS is licensed under the Eclipse Public License
Nitpick: please start each sentence on a new line (following the style guide). Also remove the extra space after the open parenthesis.

2020-07-07 23:09 UTC, dirk-thomas commented on articles/020_ros_with_dds.md
> +So, just as an example, if the default implementation is Connext, but someone wants to use one of the Apache 2 options like Fast DDS or Cyclone DDS, they simply need to recompile the ROS source code
While updating the license and changing the vendor names I would suggest to also update the surrounding information. Connext isn't the default - Fast DDS is. "Flipping some options" isn't really helpful without mentioning them - and afaik there shouldn't be any need for options - just rebuilding from source with the desired RMW implementation present should make it usable.

2020-07-08 14:12 UTC, RamziKaroui commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
From Version 6  shared memory is provided with LGPL licensing for Commercial Edition. If the intension is to only scope the Apache license V2.0 of the Opensplice Community version, let's make that clear in the document.

2020-07-08 15:47 UTC, dirk-thomas commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
The information doesn't have to be limited to the community version. But if the feature is only available in the commercial edition than that should be mentioned explicitly.

2020-07-09 01:48 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +ADLINK also contributes to Eclipse Cyclone DDS [https://github.com/eclipse-cyclonedds/cyclonedds] (https://www.adlinktech.com/en/CycloneDDS).  Cyclone DDS is licensed under the Eclipse Public License
```suggestion
ADLINK also contributes to [Eclipse Cyclone DDS](https://github.com/eclipse-cyclonedds/cyclonedds) (see https://www.adlinktech.com/en/CycloneDDS).
Cyclone DDS is licensed under the [Eclipse Public License - v 2.0](https://www.eclipse.org/legal/epl-2.0/).
```

2020-07-09 01:51 UTC, gbiggs commented on articles/020_ros_with_dds.md
> +So, just as an example, if the default implementation is Connext, but someone wants to use one of the Apache 2 options like Fast DDS or Cyclone DDS, they simply need to recompile the ROS source code
```suggestion
So, just as an example, if the default implementation is Fast DDS, but someone wants to use a commercial implementation like Connext, they simply need to change the `RMW_IMPLEMENTATION` environment variable and relaunch their nodes to change the underlying DDS implementation to Connext.
```

2020-07-09 09:52 UTC, RamziKaroui commented on articles/020_ros_with_dds.md
> +From ADLINK's website, they support TCP Since OpenSplice v6.4, supports shared memory as a transport and as an in-memory database.
That makes sense. The feature is available in the commercial edition.

2020-07-21 21:18 UTC, dirk-thomas commented
@RamziKaroui Friendly ping.

2021-01-20 16:29 UTC, clalancette commented
There's been no response to this for quite a while, so I'm going to go ahead and close it out.  Feel free to reopen and fix the review feedback.

2021-01-20 16:29 UTC, closed without merging